### ISSUE TITLE
Add LOD views to search/browse and works pages

### ISSUE THREAD

**Issue by wsalesky** [LiteratureInContext/LiC-app#109]

**Comment by wsalesky** [comment]
Note to self: 
Individual works pages done. Need to work on integration with layout. 
Todo: search/browse pages, layout considerations needed.

**Comment by jobrien62** [comment]
Working on these today and tomorrow, and have a list of things to review. Want to clean it up before sending….. John

**Comment by jobrien62** [comment]
I love the LOD visualizations, both at the level of the individual text and across the corpus. It really does put a premium on excellent TEI, and I'm a little daunted, to be honest, at the work involved in going through the TEI we already have to bring it up to speed. And possibly to enhance, so that publication location would be visually distinct from location mentions (different color?). Or authors, editors, annotators each visually distinct as well?
The Persons and Places graph doesn't show anything other than the circles, though when I click, I get taken to the information.
Sorry for neglecting all this; the chairing stuff has been veering from one emergency to the next. We're between emergencies right now.

**Comment by wsalesky** [comment]
@jobrien62 I think I can make the distinct color for the different types of location mentions and different types of persons, I will check the data, but I believe all of that is already in the TEI. 

The issue on the Persons and Places graph sounds like a bug. I will try to get it sorted out tomorrow.

**Comment by jobrien62** [comment]
Sounds good!

**Comment by wsalesky** [comment]
@jobrien62 I have made some adjustments to the graphs. Unfortunatly I can not color places and people differently depending on the relationship, because some people and places have multiple relationship types. Dublin is a good example, it is mentioned in Frankenstein and it is also a Place of Publication for Evelina; or, A Young Lady's Entrance into the World.  I added relationship text when you mouse over a node, so that might help clarify. We can investigate other methods as well. Maybe we can color code the 'edges' (the lines that connect the nodes and indicate the relationships).

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 This issue is waiting for review. If it is approved I can move it to the master branch.

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 I think this issue has been resolved? Just checking in on the remaining open issues.

**Comment by tonyahowe** [comment]
This looks great! Thank you, Winona!
