### ISSUE TITLE
No save to PDF

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#143]
https://github.com/LiteratureInContext/LiC-data/issues/29#issue-1397673045

**Comment by tonyahowe** [comment]
It doesn't look like we can save to PDF anymore

**Comment by wsalesky** [comment]
@wsalesky Note to self: 

There are errors in the PDF generation due to things like duplicate IDs. This will continue to be an issue for coursepacks. Will need some way around dup ids while still being able to use functions like footnotes and internal links. 

This is a good test case coursepack: 
https://anthologydev.lib.virginia.edu/coursepack/EN231LiteratureoftheBritishIsles4

**Comment by wsalesky** [comment]
@tonyahowe Do you want to be able to follow internal links in the pdf and epub versions? If not, I will just not translate id from the TEI, if you do I will have to come up with some way of processing them so they still work.

**Comment by tonyahowe** [comment]
The PDFs should basically use the note ids to point readers to the endnotes/footnotes; they don't need to be live, though any links out from the notes should be there. 

For ePubs, the notes should appear not in-line with the regular text, as is currently the case with ePubs--I'm not sure if ePubs can do popups, or if they should also (as with PDFs) appear like references to static footnotes/endnotes.

**Comment by wsalesky** [comment]
Okay, if they do not need to be live, I am going to turn that feature off at least for now. We can revisit at a later date.

**Comment by wsalesky** [comment]
Fixed.
