### ISSUE TITLE
Linked Data issues

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#155]
I get an error when attempting to reach the text through the list of persons. 

https://user-images.githubusercontent.com/1153464/196509709-3f08d6aa-a678-490c-86de-d8426c49f30a.mov

Also, people in the persons list are either "mention" or "person"--what is the logic here? What differentiates them? There is also some weird text appearing:

<img width="778" alt="Screen Shot 2022-10-18 at 1 57 26 PM" src="https://user-images.githubusercontent.com/1153464/196509401-05791546-6946-42e7-8c19-e5f843368143.png">

**Comment by wsalesky** [comment]
Fixed. 

They should have 'author' or 'editor' if that is the persName role in the TEI, otherwise they are 'mentioned' in the work. There is a number after the mentioned to let you know how many times in each particular work they are mentioned.  The person data was out of date, not sure why. But that is why this function was not working.
