### ISSUE TITLE
Linked Data Display on pages

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#174]
Currently all the pages that have linked data in the XML will show the network diagram of people and places when "linked data" is clicked. 

**Can we change this to display the map?** This is a better representation of the information, given that there are no external linkages that would make the network diagram more interesting.

**Comment by wsalesky** [comment]
@tonyahowe what kind of map data would you like to see? The default will load the places mentioned in the current TEI with a point for every work in the database that also mentions that place. 

Example: Against Pleasure mentions the London, the default scenario will show London with 52 data points, because 52 records also mention London.  OR I can just have a single point for the current record. 

Example 1:
<img width="1537" alt="Screenshot 2023-10-20 at 8 27 34 AM" src="https://github.com/LiteratureInContext/LiC-app/assets/1168206/79d2f5f1-56c1-4e8f-a2b2-6ee1578a3739">

Example 2:
<img width="1559" alt="Screenshot 2023-10-20 at 8 28 03 AM" src="https://github.com/LiteratureInContext/LiC-app/assets/1168206/c983d8b8-a3bd-4b16-b7f4-88a08ac944aa">

**Comment by tonyahowe** [comment]
I think the ones related to this text--that's what the existing linked data viz does, just with people.

**Comment by wsalesky** [comment]
Example 2?
