### ISSUE TITLE
Equiano page images

### ISSUE THREAD

**Issue by jobrien62** [LiteratureInContext/LiC-app#77]
Equiano page images are not showing; are the file names for the images formatted in a way that exist cannot read them?

**Comment by wsalesky** [comment]
@jobrien62 Can I have a link to the problematic page? Thanks!

**Comment by jobrien62** [comment]
Winona:

The page is this one: https://anthologydev.lib.virginia.edu/work/Equiano/equiano-interesting-narrative. If you try to get the “page Images,” you get this. One worry is that the file names of the images are too long or in a format that the database does not like. I’ll admit to not having checked every bit of the xml to compare the file names of the images with the xml, but it validates fine, and in other cases, when there’s a mismatch between the xml and the file name for an image or two, you simply get a blank image in that spot, not something like this. Thanks for investigating. John


[cid:image001.png@01D559C2.ED10B400]

**Comment by wsalesky** [comment]
@jobrien62 It looks like my paging mechanism is having some trouble with the TEI formatting of this file. I will have to fiddle with the XQuery.

**Comment by tonyahowe** [comment]
I will take a look at it too.

**Comment by wsalesky** [comment]
@tonyahowe It has something to do with with the two text elements in this TEI document (unique in the collection so far, I think) and this code: https://github.com/LiteratureInContext/LiC-app/blob/master/modules/content-negotiation/tei2html.xqm#L128

Which leads to this code: https://github.com/LiteratureInContext/LiC-app/blob/master/modules/lib/data.xqm#L253

The bug is not immediately apparent to me, but I'm sure it is fixable.

**Comment by tonyahowe** [comment]
Yes, I see! @jobrien62 it seems the problem is because both volumes of Equiano's Narrative are contained in the same XML file. It would probably be better either to separate them and develop a way to connect the volumes, or, as I've done in Frankenstein, just include all the volumes as DIVs, which isn't idea.@wsalesky -- do you have any thoughts on the best solution?

**Comment by wsalesky** [comment]
Is the two tei:text elements valid TEI? If so, and this makes the most sense for the data then we should change the XQuery to be able to handle this permutation. I will be able to take a serious look at it on Monday.

**Comment by tonyahowe** [comment]
It validates in Oxygen--but typically, it's used for things published in a single volume. In this case, and in the Frankenstein text, there are multiple volumes, each published as separate texts. It would be more appropriate to have volumes in individual XML files that are somehow linked, so readers could open each one after the other.

**Comment by tonyahowe** [comment]
The other way to do it might be to use `<floatingText>` as a way to indicate multiple whole sources in one document. But it may be necessary to have some way to navigate in longer texts, perhaps by `<div>` or by `<head>`s? I'm experimenting with Equiano-test

**Comment by jobrien62** [comment]
Thanks for experimenting; I cannot do all that much with the site today. We’ll probably face this issue of multiple volumes a good deal with older long works. (Gulliver’s Travels is four volumes, for example). John
